const mainSkills = [  // -> 14
  "Business Analysis",
  "Project Management",
  "Sales Automation (Salesbuzz)",
  "Software Implementation & Support",
  "Data Analysis & Reporting",
  "Process Optimization",
  "Vendor Management",
  "Technical Skills",
  "Programming Knowledge",
  "Digital Transformation",
  "Training & Communication",
  "Soft Skills"
];

const allSkills = [ // -> 115
  "Training Delivery",
  "Reporting & Analysis",
  "Software Configuration Management",
  "Corrective Actions",
  "Business Applications",
  "Resource Planning",
  "Operational Efficiency",
  "Business Process",
  "Support Management",
  "Business Continuity",
  "Application Support Management",
  "Microsoft Power BI",
  "Emerging Technologies",
  "Business Solution",
  "Business Intelligence (BI)",
  "Retail",
  "Product Development",
  "Client Requirements",
  "Technology Trends",
  "Timelines",
  "Presentations",
  "User Provisioning",
  "Service Delivery",
  "Role-Based Access Control (RBAC)",
  "Vendor Relations",
  "Vendor Management",
  "Service Levels",
  "Hardware Support",
  "Project Planning",
  "Salesforce Automation",
  "Documentation",
  "Project Delivery",
  "Creative Problem Solving",
  "System Performance",
  "Statutory Accounting Principles (SAP)",
  "Leadership",
  "Daily Operations",
  "Resource Allocation",
  "Organization Skills",
  "Operations Management",
  "Operations",
  "Key Performance Indicators",
  "Sales Development",
  "Product Knowledge",
  "Partner Relationship Management",
  "Performance Monitoring",
  "Technology Implementation",
  "Project Implementation",
  "Digital Transformation",
  "Microsoft Azure",
  "Networking",
  "User Training",
  "Daily Reports",
  "Spoken English",
  "Negotiation",
  "Attention to Detail",
  "User Experience (UX)",
  "Technical Specs",
  "SQL",
  "Troubleshooting",
  "Project Management",
  "Problem Solving",
  "Business Requirements",
  "Sales Buzz",
  "Computer Hardware",
  "Computer Software Training",
  "Coding Languages",
  "Management",
  "Microsoft Office",
  "Programming Languages",
  "Web Development",
  "C++",
  "Software Project Management",
  "Enterprise Software",
  "Software Installation",
  "Soft Skills",
  "Software Design",
  "Software Quality Assurance",
  "Software Implementation",
  "Software Industry",
  "ERP Software",
  "Communication",
  "E-commerce",
  "Strategic Communications",
  "Corporate Communications",
  "Internal Communications",
  "Business Strategy",
  "Business Development",
  "Analytical Skills",
  "Business Analysis",
  "Data Analysis",
  "Requirements Analysis",
  "Policy Analysis",
  "Root Cause Analysis",
  "Competitive Analysis",
  "Market Analysis",
  "Systems Analysis",
  "Software Deployment",
  "Sales Buzz | Sales Force Automation Solution"
];